name: Repo Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Delete old packages
        uses: SmartsquareGmbH/delete-old-packages@v0.8.1
        with:
          keep: 1
          version-pattern: "^build-.*$"
