name: Repo Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  cleanup-prototype-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions: write-all
    steps:
      - name: Delete old packages
        uses: actions/delete-package-versions@v5
        with:
          min-versions-to-keep: 0
          package-name: crystalpilot-prototype
          package-type: "container"
