name: Release Image

on:
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions: write-all
    env:
      GIT_STRATEGY: clone
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 20
          lfs: true
      - name: Parse version
        run: echo "VERSION=$(cat pyproject.toml | grep "version =" | head -n 1 | awk '{ print $3 }' | tr -d '"')" >> $GITHUB_ENV
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}

  publish-release:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: savannah.ornl.gov/ndip/tool-sources/single-crystal-diffraction/crystalpilot
    permissions: write-all
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NDIP_DOCKER_REGISTRY }}
          username: ${{ secrets.NDIP_DOCKER_USER }}
          password: ${{ secrets.NDIP_DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Parse version
        run: echo "VERSION=$(cat pyproject.toml | grep "version =" | head -n 1 | awk '{ print $3 }' | tr -d '"')" >> $GITHUB_ENV
      - name: Check image already exists
        run: if [ -n "$(docker manifest inspect ${{ env.IMAGE_NAME }}:${{ env.VERSION }})" ]; then echo "Image already exists, update the version and try again." && exit 1; fi
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: dockerfiles/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ env.VERSION }}
